from . import common
from . import dentist
from . import config
from . import patient
from . import appointment
from . import treatment
from . import plan
from . import prescription
from . import clinical
from . import dashboard
